version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.9-node
    working_directory: /go/src/github.com/singnet
    environment:
      SINGNET_REPOS: /go/src/github.com/singnet
    steps:
    - run:
        name: Install tools
        command: |
          # install protobuf
          sudo apt-get -y install golang-goprotobuf-dev golint
          # install IPFS
          wget https://dist.ipfs.io/go-ipfs/v0.4.17/go-ipfs_v0.4.17_linux-amd64.tar.gz
          tar xvfz go-ipfs_*.tar.gz
          cp ./go-ipfs/ipfs $GOPATH/bin
          # Installl Python
          sudo apt-get -y install python3 python3-pip
          # Install other
          sudo apt-get -y install libudev-dev libusb-1.0-0-dev
    - run:
        name: Build platform-contracts
        command: |
          cd $SINGNET_REPOS
          git clone https://github.com/singnet/platform-contracts.git
          cd platform-contracts
          npm install
          npm install ganache-cli
